      
name: Build

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectBaseDir: './'
          entryPoint: ${{ secrets.SONAR_HOST_URL }}
          args: ${{ secrets.SONAR_TOKEN }}



